# Generated by Django 5.1.1 on 2025-01-03 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Pagado', 'Pagado'), ('En mora', 'En mora')], default='Activo', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garantía',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_garantia', models.CharField(max_length=50)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.credito')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], max_length=20)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.credito')),
            ],
        ),
        migrations.AddField(
            model_name='credito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.usuario'),
        ),
    ]
